---

- name: Install homebrew only on MacOSX platform
  include: homebrew.yml
  when: ansible_distribution == 'MacOSX'

- name: Install linuxbrew only on Linux platforms
  include: linuxbrew.yml
  when: ansible_system == 'Linux'

# TODO fail/finish if brew is not installed/supported at this point

- name: tap very common external homebrew repositories
  disp_homebrew_tap: tap={{ item }}
  with_items:
    - homebrew/versions
    - homebrew/completions

- name: tap more external homebrew repositories
  disp_homebrew_tap: tap={{ item }}
  with_items: "{{ homebrew.taps|default([]) }}"

- name: update homebrew formulaes and upgrade already installed software
  disp_homebrew: update_homebrew=yes upgrade_all=yes
  when: homebrew.upgrade_all

- name: Use Hombrew Cask only on MacOSX platform
  include: homebrew_cask.yml
  tags: homebrew_cask
  when: ansible_distribution == 'MacOSX'

- name: install requested homebrew packages
  disp_homebrew:
    name: "{{ item.name|default(item) }}"
    install_options: "{{ item.install_options|default([]) }}"
  with_items: "{{ homebrew.packages|default([]) }}"
