os:   [ linux, osx ]
sudo: required

before_install: ./tests/travis/$TRAVIS_OS_NAME/clean.sh
install:
  - ./tests/travis/$TRAVIS_OS_NAME/install.sh
  - sudo pip install ansible-lint

script:
  - env
  - ./tests/travis/run.sh
  - ./tests/travis/check.sh

env:
  global:
    - DISPANSIBLE_GALAXY=yes
