#!/bin/bash

export ANSIBLE_NOCOWS=1
export ANSIBLE_HASH_BEHAVIOUR=merge

OS=linux
ASK_SUDO_PASS=''
TAGS=$1
GALAXY=yes
GALAXY_FORCE="--force" # or disable with ""

if [ "$TAGS" == "" ]; then
  TAGS=all
fi

OS_FAMILY=`uname -s`
if [ "$OS_FAMILY" == "Darwin" ]; then
  OS=macosx
#  ASK_SUDO_PASS='--ask-sudo-pass'
fi

cd ansible

export ANSIBLE_ROLES_PATH=`pwd`/galaxy
if [ "$GALAXY" == "yes" ]; then
  rm -rf $ANSIBLE_ROLES_PATH
  ansible-galaxy install $GALAXY_FORCE --roles-path $ANSIBLE_ROLES_PATH --role-file galaxy.yml
fi

ansible-playbook\
 $ASK_SUDO_PASS\
 -v\
 --sudo --sudo-user=$USER\
 --connection=local\
 --extra-vars=os=$OS\
 --extra-vars='@../settings.yml'\
 --inventory-file=inventories/$OS\
 --module-path=library\
 --tags=$TAGS\
 playbook.yml
