#!/bin/bash

ASK_SUDO_PASS='' # '--ask-sudo-pass' is required on system without password-less sudo
TAGS=$1

ANSIBLE_HOME=$PWD/ansible

if [ -z "$DISPANSIBLE_SETTINGS_DIR" ]; then
  DISPANSIBLE_SETTINGS_DIR=$PWD/settings
fi

OS=linux
OS_FAMILY=`uname -s`
if [ "$OS_FAMILY" == "Darwin" ]; then
  OS=macosx
fi

if [ -z "$DISPANSIBLE_GALAXY" ]; then
  DISPANSIBLE_GALAXY=no
fi
GALAXY_ROLES_PATH=$ANSIBLE_HOME/galaxy
GALAXY_FILE=$ANSIBLE_HOME/galaxy.yml
GALAXY_FORCE="--force" # enable with "--force" or disable with ""

if [ "$TAGS" == "" ]; then
  TAGS=all
fi

###   Ansible Galaxy   ###

if [ "$DISPANSIBLE_GALAXY" == "yes" ]; then
  if [ "GALAXY_FORCE" != "--force" ]; then
    rm -rf $GALAXY_ROLES_PATH
  fi
  ansible-galaxy install $GALAXY_FORCE --roles-path $GALAXY_ROLES_PATH --role-file $GALAXY_FILE
fi

###  Ansible Playbook  ###

cd $ANSIBLE_HOME
ansible-playbook\
 $ASK_SUDO_PASS\
 --connection=local\
 --extra-vars="@${DISPANSIBLE_SETTINGS_DIR}/private.yml"\
 --extra-vars="@${DISPANSIBLE_SETTINGS_DIR}/${OS}-software.yml"\
 --extra-vars="@${DISPANSIBLE_SETTINGS_DIR}/common-software.yml"\
 --inventory-file=inventories/$OS\
 --tags=$TAGS\
 playbook.yml
