#!/bin/bash

OS=linux

OS_FAMILY=`uname -s`
if [ "$OS_FAMILY" == "Darwin" ]; then
  OS=macosx
fi

cd ansible

ansible-playbook --sudo --sudo-user=$USER --connection=local --extra-vars=os=$OS --inventory-file=inventories/$OS --module-path=library --tags=$1 playbook.yml
