---

# FIXME: split between "personal/private" settings and "software selection"

skipped_roles: []
# Put the role names of the software you don't want to install in the 'skipped_roles' list 
#  - dummy (and don't forget to remove the empty list above ([])).

git:
  force:      no
  user:
    fullname: 'Gilles Cornu'
    email:    'git@gilles.cornu.name'

homebrew:
  upgrade_all:   no

  # see ...
  taps:
    - peco/peco

  # see available packages at http://braumeister.org
  packages:
    # Base Tools:
    - bash
    - coreutils
    - gpg
    - gnu-sed
    - peco
    - tree
    - vim

    # Network Tools
    - curl
    - nmap
    - wget

    # Developer Tools:
    - liquibase
    - llvm
    - maven
    - subversion

  # see available casks at http://caskroom.io
  casks:
    # Web Tools:
    - firefox
    - google-chrome

    # Office Tools:
    - libreoffice

    # Developer Tools:
    - sourcetree
    - intellij-idea
    - lighttable
    - sublime-text
    - java

    # DevOps Tools:
    - packer

    # Higher Productivity Tools:
    - spotify

nodejs:
  global_packages:
    - bower
    - grunt-cli
    - git-travis
    - yo

rvm:
  rubies:
    - ruby-1.9.3
    - ruby-2.0.0
    - ruby-2.1
    - ruby-2.2
    # - rbx (disabled until missing llvm-config is solved on mac platform)
    # - jruby (disabled until maven setup is organized for linux platform)

vagrant:
  version: 1.7.2
  plugins:
    - vagrant-cachier
    - vagrant-digitalocean
    - vagrant-hostmanager
    - vagrant-vbguest

virtualbox:
  version: 4.3.20
  build:   96996
