---

  # At the moment, a patched version of the apt_repository is embedded to support
  # a custom base_codename value, which is required when installing on LinuxMint for instance.
  # see https://github.com/ansible/ansible-modules-core/pull/190
  # TODO: maybe implement ansible_lsb_base_codename as a custom fact...
- name: install git-core ppa repository to get latest stable version
  disp_apt_repository:
    repo:           ppa:git-core/ppa
    update_cache:   yes
    base_codename:  '{{ ansible_lsb_base_codename | default(ansible_lsb.codename) }}'

- name: install git packages from git-core ppa
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - git-core
