- name: Build my Workstation <3 <3 <3 :-)
  hosts:
    - mac_box
    - linux_box

  pre_tasks:
    # FIXME this check only works when no ansible tags are used!
    #       another approach will consists in adding similar checker for each software role
    - name: Check for unsupported platform
      fail: msg="The operating system {{ ansible_distribution }} / {{ ansible_os_family }}) is not currently supported."
      when: "ansible_distribution not in ['Debian', 'Linuxmint', 'MacOSX', 'Ubuntu']"

  roles:

################################################¬
# First Things
################################################¬

  - {
      role: homebrew,
      homebrew: '{{ software.homebrew }}',
      tags: homebrew,
      when: software.homebrew is defined and software.homebrew
    }

################################################
# Low Level Stuff
################################################

  - {
      role: openzfs,
      tags: openzfs,
      when: software.openzfs
    }

################################################
# Base Tools
################################################

  - {
      role: git,
      git: '{{ settings.git }}',
      tags: git,
      when: software.git
    }

################################################¬
# Virtualization Tools
################################################¬

  - {
      role: vagrant,
      vagrant: '{{ software.vagrant }}',
      tags: vagrant,
      when: software.vagrant is defined and software.vagrant
    }
#
################################################¬
# Missing Things
################################################¬

################################################¬
# Last Things
################################################¬

  - {
      role: home,
      tags: home,
      when: software.home
    }

  tasks:

################################################
# Base Tools
################################################

  - include: "{{ os }}/shell_tools.yml"
    tags: shell_tools
    when: software.shell_tools

  - include: "{{ os }}/editor_tools.yml"
    tags: editor_tools
    when: software.editor_tools

  - include: "{{ os }}/network_tools.yml"
    tags: network_tools
    when: software.network_tools

  - include: "{{ os }}/nodejs.yml"
    tags: nodejs
    when: software.nodejs
    vars:
      nodejs:
        global_packages:
          - bower
          - grunt-cli
          - git-travis
          - yo

################################################
# Virtualization Tools
################################################

  - include: "{{ os }}/virtualbox.yml"
    tags: virtualbox
    when: software.virtualbox
    vars:
      virtualbox:
        version: 4.3.20
        build:   96996

