- name: Build my Workstation <3 <3 <3 :-)
  hosts:
    - mac_box
    - linux_box

  sudo: yes
  sudo_user: '{{ ansible_ssh_user }}'

  pre_tasks:
    # FIXME this check only works when no ansible tags are used!
    #       another approach will consists in adding similar checker for each software role
    - name: Check for unsupported platform
      fail: msg="The operating system {{ ansible_distribution }} / {{ ansible_os_family }}) is not currently supported."
      when: "ansible_distribution not in ['Debian', 'Linuxmint', 'MacOSX', 'Ubuntu']"

  roles:

################################################¬
# First Things
################################################¬

  - {
      role: homebrew,
      tags: homebrew,
      when: "'homebrew' not in skipped_roles"
    }

################################################
# Low Level Stuff
################################################

  - {
      role: openzfs,
      tags: openzfs,
      when: "'openzfs' not in skipped_roles"
    }

################################################
# Base Tools
################################################

  - {
      role: git,
      tags: git,
      when: "'git' not in skipped_roles"
    }

################################################
# Programming Language Tools
################################################


  # By default this role makes a system-wide setup,
  # but here we want a user setup.
  - {
      role: 'rvm_io.rvm1-ruby',
      rvm1_user: '{{ ansible_env.USER }}',
      rvm1_install_path: '{{ ansible_env.HOME }}/.rvm',
      rvm1_install_flags: '--auto-dotfiles --autolibs=homebrew --user-install',
      rvm1_rubies: '{{ rvm.rubies }}',
      tags: rvm,
      when: "'rvm' not in skipped_roles"
    }

  - {
      role: nodejs,
      tags: nodejs,
      when: "'nodejs' not in skipped_roles"
    }

################################################¬
# Virtualization Tools
################################################¬

  - {
      role: virtualbox,
      tags: virtualbox,
      when: "'virtualbox' not in skipped_roles"
    }

  - {
      role: vagrant,
      tags: vagrant,
      when: "'vagrant' not in skipped_roles"
    }

################################################¬
# Last Things
################################################¬

  - {
      role: home,
      tags: home,
      when: "'home' not in skipped_roles"
    }
