- name: Build my Workstation <3 <3 <3 :-)
  hosts:
    - mac_box
    - linux_box

  gather_facts: yes

  become: yes
#  become_user: '{{ ansible_ssh_user }}'
#  become_user: '{{ansible_env.USER}}'
#  become_user: vagrant

  pre_tasks:

    - debug: msg="{{ ansible_ssh_user }}"
    - debug: msg="{{ ansible_env }}"

    # FIXME this check only works when no ansible tags are used!
    #       another approach will consists in adding similar checker for each software role
    - name: Check for unsupported platform
      fail: msg="The operating system {{ ansible_distribution }} / {{ ansible_os_family }}) is not currently supported."
      when: "ansible_distribution not in ['Debian', 'Linuxmint', 'MacOSX', 'Ubuntu']"

  roles:

################################################¬
# First Things...
################################################¬

  - {
      role: home,
      tags: home,
      when: "'home' not in skipped_roles"
    }

  - {
      role: git,
      tags: git,
      when: "'git' not in skipped_roles"
    }

################################################¬
# Package Managers
################################################¬

  - {
      role: apt,
      tags: apt,
      when: "'apt' not in skipped_roles"
    }

  - {
      role: homebrew,
      tags: homebrew,
      when: "'homebrew' not in skipped_roles"
    }

################################################
# Low Level Stuff
################################################

  - {
      role: openzfs,
      tags: openzfs,
      when: "'openzfs' not in skipped_roles"
    }

################################################
# Base Tools
################################################

  - {
      role: ohmyzsh,
      tags: ohmyzsh,
      when: "'ohmyzsh' not in skipped_roles"
    }

################################################
# Programming Language Tools
################################################

  - {
      role: oracle_jdk_ubuntu,
      sudo_user: root,
      oracle_jdk_switcher_enabled:      yes,
      oracle_jdk_switcher_version:      'e501c74033e475a0b6938987d912cf0c4b0baa06',
      oracle_jdk_java_versions:         [7, 8],
      oracle_jdk_java_version_default:  8,
      tags: oracle_jdk,
      when: "'oracle_jdk' not in skipped_roles and ansible_system == 'Linux'" # FIXME improve cross-platformism (Rehat family, etc.)
    }

  - {
      role: clojure_tools,
      tags: clojure_tools,
      when: "'clojure_tools' not in skipped_roles"
    }

  # By default this role makes a system-wide setup,
  # but here we want a user setup.
  - {
      role: 'rvm',
      rvm1_user: '{{ ansible_env.USER }}',
      rvm1_install_path: '{{ ansible_env.HOME }}/.rvm',
      rvm1_install_flags: '--auto-dotfiles --autolibs=enable --user-install',
      rvm1_rubies: '{{ rvm.rubies }}',
      tags: rvm,
      when: "'rvm' not in skipped_roles"
    }

  - {
      role: nodejs,
      tags: nodejs,
      when: "'nodejs' not in skipped_roles"
    }

#################################################¬
# Text Editors, IDE,...
################################################¬

  - {
      role: sublimetext,
      tags: sublimetext,
      when: "'sublimetext' not in skipped_roles"
    }

###############################################¬
# Virtualization Tools
################################################¬

  - {
      role: virtualbox,
      tags: virtualbox,
      when: "'virtualbox' not in skipped_roles"
    }

  - { # FIXME: encapsulate in a platform-agnostic role to address Mac,Redhat-family,...
      role: docker_ubuntu,
      tags: docker,
      sudo_user: root,
      docker_group_members: [ '{{ ansible_env.USER }}' ],
      when: "'docker' not in skipped_roles and ansible_os_family in ['Debian', 'Linuxmint']"
    }

  - {
      role: vagrant,
      tags: vagrant,
      when: "'vagrant' not in skipped_roles"
    }

################################################¬
# "Optional" stuff (!)
################################################¬

  - {
      role: spotify_ubuntu,
      tags: spotify,
      sudo_user: root,
      when: "'spotify' not in skipped_roles and ansible_system == 'Linux'" # FIXME improve cross-platformism (Rehat family, etc.)
    }

################################################¬
# Last Things
################################################¬


