- name: Build my Workstation <3 <3 <3 :-)
  hosts:
    - mac_box
    - linux_box

  pre_tasks:
    # FIXME this check only works when no ansible tags are used!
    #       another approach will consists in adding similar checker for each software role
    - name: Check for unsupported platform
      fail: msg="The operating system {{ ansible_distribution }} / {{ ansible_os_family }}) is not currently supported."
      when: "ansible_distribution not in ['Debian', 'Linuxmint', 'MacOSX', 'Ubuntu']"

  roles:
    - {
        role: homebrew,
        homebrew: '{{ software.homebrew }}',
        tags: homebrew,
        when: software.homebrew
      }

  tasks:

################################################
# Low Level Stuff
################################################

  - include: "{{ os }}/openzfs.yml"
    tags: openzfs
    when: software.openzfs

################################################
# Base Tools
################################################

  - include: "{{ os }}/shell_tools.yml"
    tags: shell_tools
    when: software.shell_tools

  - include: "{{ os }}/editor_tools.yml"
    tags: editor_tools
    when: software.editor_tools

  - include: "{{ os }}/network_tools.yml"
    tags: network_tools
    when: software.network_tools

  - include: "{{ os }}/git.yml"
    tags: git
    when: software.git
    vars:
      git:
        user:
          fullname: 'Gilles Cornu'
          email:    'git@gilles.cornu.name'

  - include: "{{ os }}/nodejs.yml"
    tags: nodejs
    when: software.nodejs
    vars:
      nodejs:
        global_packages:
          - bower
          - grunt-cli
          - git-travis
          - yo

  - include: "{{ os }}/sourcetree.yml"
    tags: sourcetree
    when: software.sourcetree

################################################
# Virtualization Tools
################################################

  - include: "{{ os }}/packer.yml"
    tags: packer
    when: software.packer

  - include: "{{ os }}/virtualbox.yml"
    tags: virtualbox
    when: software.virtualbox
    vars:
      virtualbox:
        version: 4.3.20
        build:   96996

  - include: "{{ os }}/vagrant.yml"
    tags: vagrant
    when: software.vagrant

################################################
# IDE, Editor, ...
################################################

  - include: "{{ os }}/intellij_idea.yml"
    tags: intellij_idea
    when: software.intellij_idea

  - include: "{{ os }}/sublimetext.yml"
    tags: sublimetext
    when: software.sublimetext

################################################
# Mandatory Optionals
################################################

  - include: "{{ os }}/spotify.yml"
    tags: spotify
    when: software.spotify

################################################
# Office Material
################################################

  - include: "{{ os }}/libreoffice.yml"
    tags: libreoffice
    when: software.libreoffice

################################################
# Last Things
################################################

  - include: "common/home.yml"
    tags: home
    when: software.home
