---

#FIXME these settings only apply in Linux environments (for the moment)

vagrant:
  #FIXME the version option is only considered in Linux environment.
  #      on mac, homebrew only can provide the "latest" version. 
  version: 1.8.3
  plugins:
    - vagrant-cachier
