---

- name: tap external homebrew repositories
  homebrew_tap: tap={{ item }}
  with_items:
    - homebrew/versions
    - homebrew/completions

# TODO add some idempotence creates conditions
# TODO why homebrew module fails ...?
- name: install homebrew cask
  command: brew install caskroom/cask/brew-cask

